# Generated by Django 5.1 on 2024-09-06 17:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('stripe_product_id', models.CharField(blank=True, max_length=50, null=True)),
                ('stripe_price_id', models.CharField(blank=True, max_length=50, null=True)),
                ('interval', models.CharField(max_length=50)),
            ],
        ),
    ]
