# Generated by Django 5.1 on 2024-09-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserregistration',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
