# Generated by Django 5.1 on 2024-10-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_customuserregistration_is_logged_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserregistration',
            name='fcm_token',
            field=models.CharField(default='sizbfgrvlzieruglue', max_length=50),
            preserve_default=False,
        ),
    ]
