# Generated by Django 5.1 on 2024-10-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='interval_count',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
    ]
