# Generated by Django 5.1 on 2024-09-06 17:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GymDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gym_name', models.CharField(max_length=30)),
                ('gym_owner_first_name', models.CharField(max_length=50)),
                ('gym_owner_last_name', models.CharField(max_length=50)),
                ('gym_address', models.CharField(max_length=100)),
                ('gym_phone_number', models.CharField(max_length=20)),
                ('gym_email', models.EmailField(max_length=254)),
                ('promo_code_offers', models.BooleanField(default=False)),
                ('promo_code', models.CharField(max_length=30)),
                ('stripe_account_id', models.CharField(max_length=100)),
            ],
        ),
    ]
