# Generated by Django 5.1 on 2024-10-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='fcm_token',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
