# Generated by Django 5.1 on 2024-09-06 17:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('plan_status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('inactive', 'Inactive'), ('pending', 'Pending')], max_length=10)),
                ('plan_name', models.CharField(max_length=30)),
                ('plan_start_date', models.DateTimeField()),
                ('plan_end_date', models.DateTimeField()),
                ('stripe_subscription_id', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
