# Generated by Django 5.1 on 2024-09-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymproducts',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
