# Generated by Django 5.1 on 2024-09-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_products', '0003_gymproducts_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymproducts',
            name='reviews',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
